import { defineConfig } from "oxlint";
import antiSlop from "ultracite/oxlint/anti-slop";
import core from "ultracite/oxlint/core";

export default defineConfig({
  extends: [core, antiSlop],
  ignorePatterns: [
    ...(core.ignorePatterns ?? []),
    ".agent/**",
    ".agents/**",
    ".claude/**",
    ".codex/**",
    ".continue/**",
    ".cursor/**",
    ".gemini/**",
    ".opencode/**",
    ".pi/**",
    ".roo/**",
    ".windsurf/**",
    "**/.superpowers/**",
    "**/.cloudflare/**",
    "**/src/generated/**",
    "**/*generated*",
    "**/skills/**",
    "**/solidity/**",
  ],
  options: { typeAware: true, typeCheck: true },
  rules: {
    // Ultracite core rules the code does not satisfy yet. The migration kept the code as it was;
    // enable these one at a time in follow-up pull requests and fix what each one reports.
    complexity: "off",
    eqeqeq: "off",
    "func-names": "off",
    "func-style": "off",
    "import/consistent-type-specifier-style": "off",
    "import/no-duplicates": "off",
    "max-classes-per-file": "off",
    "no-alert": "off",
    "no-await-in-loop": "off",
    "no-bitwise": "off",
    "no-duplicate-imports": "off",
    "no-eq-null": "off",
    "no-inline-comments": "off",
    "no-negated-condition": "off",
    "no-nested-ternary": "off",
    "no-plusplus": "off",
    "no-promise-executor-return": "off",
    "no-redeclare": "off",
    "no-script-url": "off",
    "no-shadow": "off",
    "no-use-before-define": "off",
    "oxc/approx-constant": "off",
    "oxc/no-barrel-file": "off",
    "prefer-destructuring": "off",
    "prefer-exponentiation-operator": "off",
    "prefer-named-capture-group": "off",
    "prefer-promise-reject-errors": "off",
    "prefer-template": "off",
    "promise/avoid-new": "off",
    "promise/param-names": "off",
    "promise/prefer-await-to-callbacks": "off",
    "promise/prefer-await-to-then": "off",
    "require-await": "off",
    "require-unicode-regexp": "off",
    "sort-keys": "off",
    "typescript/array-type": "off",
    "typescript/consistent-return": "off",
    "typescript/consistent-type-definitions": "off",
    "typescript/consistent-type-imports": "off",
    "typescript/method-signature-style": "off",
    "typescript/no-confusing-void-expression": "off",
    "typescript/no-deprecated": "off",
    "typescript/no-empty-interface": "off",
    "typescript/no-empty-object-type": "off",
    "typescript/no-import-type-side-effects": "off",
    "typescript/non-nullable-type-assertion-style": "off",
    "typescript/no-non-null-assertion": "off",
    "typescript/no-unnecessary-type-assertion": "off",
    "typescript/no-unsafe-argument": "off",
    "typescript/no-unsafe-assignment": "off",
    "typescript/no-unsafe-call": "off",
    "typescript/no-unsafe-member-access": "off",
    "typescript/no-unsafe-return": "off",
    "typescript/no-unsafe-type-assertion": "off",
    "typescript/parameter-properties": "off",
    "typescript/prefer-nullish-coalescing": "off",
    "typescript/prefer-promise-reject-errors": "off",
    "typescript/prefer-regexp-exec": "off",
    "typescript/promise-function-async": "off",
    "typescript/return-await": "off",
    "typescript/strict-boolean-expressions": "off",
    "typescript/strict-void-return": "off",
    "unicorn/catch-error-name": "off",
    "unicorn/custom-error-definition": "off",
    "unicorn/escape-case": "off",
    "unicorn/filename-case": "off",
    "unicorn/import-style": "off",
    "unicorn/no-array-for-each": "off",
    "unicorn/no-array-sort": "off",
    "unicorn/no-await-expression-member": "off",
    "unicorn/no-hex-escape": "off",
    "unicorn/no-negated-condition": "off",
    "unicorn/no-useless-undefined": "off",
    "unicorn/numeric-separators-style": "off",
    "unicorn/prefer-code-point": "off",
    "unicorn/prefer-default-parameters": "off",
    "unicorn/prefer-dom-node-append": "off",
    "unicorn/prefer-dom-node-dataset": "off",
    "unicorn/prefer-export-from": "off",
    "unicorn/prefer-number-properties": "off",
    "unicorn/prefer-response-static-json": "off",
    "unicorn/prefer-set-has": "off",
    "unicorn/prefer-string-replace-all": "off",
    "unicorn/prefer-ternary": "off",
    "unicorn/prefer-type-error": "off",
    "unicorn/relative-url-style": "off",
    "unicorn/text-encoding-identifier-case": "off",
    "unicorn/throw-new-error": "off",
    "anti-slop/no-chained-type-assertions": "error",
    "anti-slop/no-conditional-empty-object-spread": "off",
    "anti-slop/no-known-value-widening": "off",
    "anti-slop/no-module-mocking": "error",
    "anti-slop/no-object-parameters": "error",
    "anti-slop/no-reflect-apply": "error",
    "anti-slop/no-reflect-get": "off",
    "anti-slop/no-runtime-typeof": "off",
    "anti-slop/no-shape-in-symbol-names": "off",
    "anti-slop/no-unknown-parameters": "off",
    "anti-slop/no-unknown-returns": "off",
    "anti-slop/no-unknown-type-aliases": "error",
    "anti-slop/no-unsafe-dictionary-type": "off",
    "anti-slop/no-widen-then-assert": "error",
    "anti-slop/require-safety-comment-for-type-assertion": "error",
    curly: ["error", "all"],
    "typescript/await-thenable": "off",
    "typescript/no-base-to-string": "off",
    "typescript/unbound-method": "off",
  },
  overrides: [
    {
      files: ["**/test/**", "**/*.test.*", "**/*.spec.*"],
      rules: { "anti-slop/require-safety-comment-for-type-assertion": "off" },
    },
    {
      // The extensions were migrated as they were. Functions passed to chrome.scripting.executeScript
      // must stay self-contained, so the autofixes must not move or merge their code.
      files: ["chrome-extensions/**"],
      rules: {
        "arrow-body-style": "off",
        curly: "off",
        "no-implicit-globals": "off",
        "no-unused-vars": "off",
        "no-useless-escape": "off",
        "object-shorthand": "off",
        "prefer-const": "off",
        "typescript/no-floating-promises": "off",
        "typescript/no-misused-promises": "off",
        "typescript/prefer-includes": "off",
        "unicorn/consistent-function-scoping": "off",
        "unicorn/no-console-spaces": "off",
        "unicorn/prefer-add-event-listener": "off",
        "unicorn/prefer-dom-node-remove": "off",
        "unicorn/prefer-dom-node-text-content": "off",
        "unicorn/prefer-module": "off",
        "unicorn/prefer-query-selector": "off",
        "unicorn/prefer-regexp-test": "off",
        "unicorn/prefer-single-call": "off",
        "unicorn/prefer-spread": "off",
      },
    },
    {
      // Zagora was migrated as it was. The library is `any`-heavy by design, and the tests throw the
      // typed error objects on purpose. Enable these one at a time in follow-up pull requests.
      files: ["packages/zagora/**"],
      rules: {
        "anti-slop/no-object-parameters": "off",
        "anti-slop/require-safety-comment-for-type-assertion": "off",
        "class-methods-use-this": "off",
        "import/no-named-as-default": "off",
        "no-throw-literal": "off",
        "no-unreachable": "off",
        "no-unused-expressions": "off",
        "no-unused-vars": "off",
        "no-warning-comments": "off",
        "typescript/ban-types": "off",
        "typescript/no-explicit-any": "off",
        "typescript/no-inferrable-types": "off",
        "typescript/no-redundant-type-constituents": "off",
        "typescript/no-this-alias": "off",
        "typescript/no-unnecessary-type-arguments": "off",
        "typescript/no-unnecessary-type-parameters": "off",
        "typescript/only-throw-error": "off",
        "typescript/restrict-template-expressions": "off",
        "typescript/use-unknown-in-catch-callback-variable": "off",
        "unicorn/consistent-function-scoping": "off",
        "unicorn/error-message": "off",
        "unicorn/no-this-assignment": "off",
        "unicorn/prefer-number-coercion": "off",
      },
    },
  ],
});
