allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - "@cloudflare/workers-types@5.20260710.1"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: ^4.1.10
  vite-plus: ^0.2.8
overrides:
  kysely: 0.28.17
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
patchedDependencies:
  "@better-auth/cimd@1.7.0-rc.1": patches/@better-auth__cimd@1.7.0-rc.1.patch
  "@better-auth/oauth-provider@1.7.0-rc.1": patches/@better-auth__oauth-provider@1.7.0-rc.1.patch
