name = "triad-auth"
main = "src/index.ts"
compatibility_date = "2026-07-09"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
workers_dev = false
preview_urls = true

[vars]
AUTH_ORIGIN = "https://triad.wgw.lol"

[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"
run_worker_first = false

[[d1_databases]]
binding = "DB"
database_name = "triad-auth"
database_id = "61519699-e934-41ec-93f4-b337a2d3e328"
migrations_dir = "migrations"
