/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as OwnerIndexRouteImport } from './routes/$owner/index'
import { Route as OwnerRepoRouteImport } from './routes/$owner/$repo'
import { Route as SettingsTokensRouteImport } from './routes/settings/tokens'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner/$repo/index'
import { Route as OwnerRepoBranchesRouteImport } from './routes/$owner/$repo/branches'
import { Route as OwnerRepoCommitsRouteImport } from './routes/$owner/$repo/commits'
import { Route as OwnerRepoSettingsRouteImport } from './routes/$owner/$repo/settings'
import { Route as OwnerRepoBlobSplatRouteImport } from './routes/$owner/$repo/blob/$'
import { Route as OwnerRepoCommitShaRouteImport } from './routes/$owner/$repo/commit/$sha'
import { Route as OwnerRepoPullsIndexRouteImport } from './routes/$owner/$repo/pulls/index'
import { Route as OwnerRepoPullsNumberRouteImport } from './routes/$owner/$repo/pulls/$number'
import { Route as OwnerRepoPullsNewRouteImport } from './routes/$owner/$repo/pulls/new'
import { Route as OwnerRepoTreeSplatRouteImport } from './routes/$owner/$repo/tree/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/$owner/',
  path: '/$owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoRoute = OwnerRepoRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTokensRoute = SettingsTokensRouteImport.update({
  id: '/settings/tokens',
  path: '/settings/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoBranchesRoute = OwnerRepoBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoCommitsRoute = OwnerRepoCommitsRouteImport.update({
  id: '/commits',
  path: '/commits',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoSettingsRoute = OwnerRepoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoBlobSplatRoute = OwnerRepoBlobSplatRouteImport.update({
  id: '/blob/$',
  path: '/blob/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoCommitShaRoute = OwnerRepoCommitShaRouteImport.update({
  id: '/commit/$sha',
  path: '/commit/$sha',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoPullsIndexRoute = OwnerRepoPullsIndexRouteImport.update({
  id: '/pulls/',
  path: '/pulls/',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoPullsNumberRoute = OwnerRepoPullsNumberRouteImport.update({
  id: '/pulls/$number',
  path: '/pulls/$number',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoPullsNewRoute = OwnerRepoPullsNewRouteImport.update({
  id: '/pulls/new',
  path: '/pulls/new',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoTreeSplatRoute = OwnerRepoTreeSplatRouteImport.update({
  id: '/tree/$',
  path: '/tree/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/$owner/$repo': typeof OwnerRepoRouteWithChildren
  '/settings/tokens': typeof SettingsTokensRoute
  '/$owner/': typeof OwnerIndexRoute
  '/$owner/$repo/branches': typeof OwnerRepoBranchesRoute
  '/$owner/$repo/commits': typeof OwnerRepoCommitsRoute
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/blob/$': typeof OwnerRepoBlobSplatRoute
  '/$owner/$repo/commit/$sha': typeof OwnerRepoCommitShaRoute
  '/$owner/$repo/pulls/$number': typeof OwnerRepoPullsNumberRoute
  '/$owner/$repo/pulls/new': typeof OwnerRepoPullsNewRoute
  '/$owner/$repo/tree/$': typeof OwnerRepoTreeSplatRoute
  '/$owner/$repo/pulls/': typeof OwnerRepoPullsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/$owner': typeof OwnerIndexRoute
  '/$owner/$repo/branches': typeof OwnerRepoBranchesRoute
  '/$owner/$repo/commits': typeof OwnerRepoCommitsRoute
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/$repo/blob/$': typeof OwnerRepoBlobSplatRoute
  '/$owner/$repo/commit/$sha': typeof OwnerRepoCommitShaRoute
  '/$owner/$repo/pulls/$number': typeof OwnerRepoPullsNumberRoute
  '/$owner/$repo/pulls/new': typeof OwnerRepoPullsNewRoute
  '/$owner/$repo/tree/$': typeof OwnerRepoTreeSplatRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/$owner/$repo': typeof OwnerRepoRouteWithChildren
  '/settings/tokens': typeof SettingsTokensRoute
  '/$owner/': typeof OwnerIndexRoute
  '/$owner/$repo/branches': typeof OwnerRepoBranchesRoute
  '/$owner/$repo/commits': typeof OwnerRepoCommitsRoute
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/blob/$': typeof OwnerRepoBlobSplatRoute
  '/$owner/$repo/commit/$sha': typeof OwnerRepoCommitShaRoute
  '/$owner/$repo/pulls/$number': typeof OwnerRepoPullsNumberRoute
  '/$owner/$repo/pulls/new': typeof OwnerRepoPullsNewRoute
  '/$owner/$repo/tree/$': typeof OwnerRepoTreeSplatRoute
  '/$owner/$repo/pulls/': typeof OwnerRepoPullsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claim'
    | '/device'
    | '/login'
    | '/new'
    | '/$owner/$repo'
    | '/settings/tokens'
    | '/$owner/'
    | '/$owner/$repo/branches'
    | '/$owner/$repo/commits'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/commit/$sha'
    | '/$owner/$repo/pulls/$number'
    | '/$owner/$repo/pulls/new'
    | '/$owner/$repo/tree/$'
    | '/$owner/$repo/pulls/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claim'
    | '/device'
    | '/login'
    | '/new'
    | '/settings/tokens'
    | '/$owner'
    | '/$owner/$repo/branches'
    | '/$owner/$repo/commits'
    | '/$owner/$repo/settings'
    | '/$owner/$repo'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/commit/$sha'
    | '/$owner/$repo/pulls/$number'
    | '/$owner/$repo/pulls/new'
    | '/$owner/$repo/tree/$'
    | '/$owner/$repo/pulls'
  id:
    | '__root__'
    | '/'
    | '/claim'
    | '/device'
    | '/login'
    | '/new'
    | '/$owner/$repo'
    | '/settings/tokens'
    | '/$owner/'
    | '/$owner/$repo/branches'
    | '/$owner/$repo/commits'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/commit/$sha'
    | '/$owner/$repo/pulls/$number'
    | '/$owner/$repo/pulls/new'
    | '/$owner/$repo/tree/$'
    | '/$owner/$repo/pulls/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimRoute: typeof ClaimRoute
  DeviceRoute: typeof DeviceRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  OwnerRepoRoute: typeof OwnerRepoRouteWithChildren
  SettingsTokensRoute: typeof SettingsTokensRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/': {
      id: '/$owner/'
      path: '/$owner'
      fullPath: '/$owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo': {
      id: '/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof OwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tokens': {
      id: '/settings/tokens'
      path: '/settings/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof SettingsTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/branches': {
      id: '/$owner/$repo/branches'
      path: '/branches'
      fullPath: '/$owner/$repo/branches'
      preLoaderRoute: typeof OwnerRepoBranchesRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/commits': {
      id: '/$owner/$repo/commits'
      path: '/commits'
      fullPath: '/$owner/$repo/commits'
      preLoaderRoute: typeof OwnerRepoCommitsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/settings': {
      id: '/$owner/$repo/settings'
      path: '/settings'
      fullPath: '/$owner/$repo/settings'
      preLoaderRoute: typeof OwnerRepoSettingsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/blob/$': {
      id: '/$owner/$repo/blob/$'
      path: '/blob/$'
      fullPath: '/$owner/$repo/blob/$'
      preLoaderRoute: typeof OwnerRepoBlobSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/commit/$sha': {
      id: '/$owner/$repo/commit/$sha'
      path: '/commit/$sha'
      fullPath: '/$owner/$repo/commit/$sha'
      preLoaderRoute: typeof OwnerRepoCommitShaRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/pulls/': {
      id: '/$owner/$repo/pulls/'
      path: '/pulls'
      fullPath: '/$owner/$repo/pulls/'
      preLoaderRoute: typeof OwnerRepoPullsIndexRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/pulls/$number': {
      id: '/$owner/$repo/pulls/$number'
      path: '/pulls/$number'
      fullPath: '/$owner/$repo/pulls/$number'
      preLoaderRoute: typeof OwnerRepoPullsNumberRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/pulls/new': {
      id: '/$owner/$repo/pulls/new'
      path: '/pulls/new'
      fullPath: '/$owner/$repo/pulls/new'
      preLoaderRoute: typeof OwnerRepoPullsNewRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/tree/$': {
      id: '/$owner/$repo/tree/$'
      path: '/tree/$'
      fullPath: '/$owner/$repo/tree/$'
      preLoaderRoute: typeof OwnerRepoTreeSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
  }
}

interface OwnerRepoRouteChildren {
  OwnerRepoBranchesRoute: typeof OwnerRepoBranchesRoute
  OwnerRepoCommitsRoute: typeof OwnerRepoCommitsRoute
  OwnerRepoSettingsRoute: typeof OwnerRepoSettingsRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
  OwnerRepoBlobSplatRoute: typeof OwnerRepoBlobSplatRoute
  OwnerRepoCommitShaRoute: typeof OwnerRepoCommitShaRoute
  OwnerRepoPullsNumberRoute: typeof OwnerRepoPullsNumberRoute
  OwnerRepoPullsNewRoute: typeof OwnerRepoPullsNewRoute
  OwnerRepoTreeSplatRoute: typeof OwnerRepoTreeSplatRoute
  OwnerRepoPullsIndexRoute: typeof OwnerRepoPullsIndexRoute
}

const OwnerRepoRouteChildren: OwnerRepoRouteChildren = {
  OwnerRepoBranchesRoute: OwnerRepoBranchesRoute,
  OwnerRepoCommitsRoute: OwnerRepoCommitsRoute,
  OwnerRepoSettingsRoute: OwnerRepoSettingsRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
  OwnerRepoBlobSplatRoute: OwnerRepoBlobSplatRoute,
  OwnerRepoCommitShaRoute: OwnerRepoCommitShaRoute,
  OwnerRepoPullsNumberRoute: OwnerRepoPullsNumberRoute,
  OwnerRepoPullsNewRoute: OwnerRepoPullsNewRoute,
  OwnerRepoTreeSplatRoute: OwnerRepoTreeSplatRoute,
  OwnerRepoPullsIndexRoute: OwnerRepoPullsIndexRoute,
}

const OwnerRepoRouteWithChildren = OwnerRepoRoute._addFileChildren(
  OwnerRepoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimRoute: ClaimRoute,
  DeviceRoute: DeviceRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  OwnerRepoRoute: OwnerRepoRouteWithChildren,
  SettingsTokensRoute: SettingsTokensRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
