/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OwnerIndexRouteImport } from './routes/$owner/index'
import { Route as OwnerRepoRouteRouteImport } from './routes/$owner/$repo/route'
import { Route as LoginPasskeyRouteImport } from './routes/login_.passkey'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner/$repo/index'
import { Route as OwnerRepoBlobRouteImport } from './routes/$owner/$repo/blob'
import { Route as OwnerRepoCommitsRouteImport } from './routes/$owner/$repo/commits'
import { Route as OwnerRepoSettingsRouteImport } from './routes/$owner/$repo/settings'
import { Route as OwnerRepoCommitShaRouteImport } from './routes/$owner/$repo/commit.$sha'
import { Route as OwnerRepoPullNumberRouteImport } from './routes/$owner/$repo/pull.$number'
import { Route as OwnerRepoPullsIndexRouteImport } from './routes/$owner/$repo/pulls.index'
import { Route as OwnerRepoPullsNewRouteImport } from './routes/$owner/$repo/pulls.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/$owner/',
  path: '/$owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoRouteRoute = OwnerRepoRouteRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPasskeyRoute = LoginPasskeyRouteImport.update({
  id: '/login_/passkey',
  path: '/login/passkey',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRepoRouteRoute,
} as any)
const OwnerRepoBlobRoute = OwnerRepoBlobRouteImport.update({
  id: '/blob',
  path: '/blob',
  getParentRoute: () => OwnerRepoRouteRoute,
} as any)
const OwnerRepoCommitsRoute = OwnerRepoCommitsRouteImport.update({
  id: '/commits',
  path: '/commits',
  getParentRoute: () => OwnerRepoRouteRoute,
} as any)
const OwnerRepoSettingsRoute = OwnerRepoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRepoRouteRoute,
} as any)
const OwnerRepoCommitShaRoute = OwnerRepoCommitShaRouteImport.update({
  id: '/commit/$sha',
  path: '/commit/$sha',
  getParentRoute: () => OwnerRepoRouteRoute,
} as any)
const OwnerRepoPullNumberRoute = OwnerRepoPullNumberRouteImport.update({
  id: '/pull/$number',
  path: '/pull/$number',
  getParentRoute: () => OwnerRepoRouteRoute,
} as any)
const OwnerRepoPullsIndexRoute = OwnerRepoPullsIndexRouteImport.update({
  id: '/pulls/',
  path: '/pulls/',
  getParentRoute: () => OwnerRepoRouteRoute,
} as any)
const OwnerRepoPullsNewRoute = OwnerRepoPullsNewRouteImport.update({
  id: '/pulls/new',
  path: '/pulls/new',
  getParentRoute: () => OwnerRepoRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/device': typeof DeviceRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/$owner/$repo': typeof OwnerRepoRouteRouteWithChildren
  '/login/passkey': typeof LoginPasskeyRoute
  '/$owner/': typeof OwnerIndexRoute
  '/$owner/$repo/blob': typeof OwnerRepoBlobRoute
  '/$owner/$repo/commits': typeof OwnerRepoCommitsRoute
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/commit/$sha': typeof OwnerRepoCommitShaRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRoute
  '/$owner/$repo/pulls/new': typeof OwnerRepoPullsNewRoute
  '/$owner/$repo/pulls/': typeof OwnerRepoPullsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/device': typeof DeviceRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/login/passkey': typeof LoginPasskeyRoute
  '/$owner': typeof OwnerIndexRoute
  '/$owner/$repo/blob': typeof OwnerRepoBlobRoute
  '/$owner/$repo/commits': typeof OwnerRepoCommitsRoute
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/$repo/commit/$sha': typeof OwnerRepoCommitShaRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRoute
  '/$owner/$repo/pulls/new': typeof OwnerRepoPullsNewRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/device': typeof DeviceRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/$owner/$repo': typeof OwnerRepoRouteRouteWithChildren
  '/login_/passkey': typeof LoginPasskeyRoute
  '/$owner/': typeof OwnerIndexRoute
  '/$owner/$repo/blob': typeof OwnerRepoBlobRoute
  '/$owner/$repo/commits': typeof OwnerRepoCommitsRoute
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/commit/$sha': typeof OwnerRepoCommitShaRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRoute
  '/$owner/$repo/pulls/new': typeof OwnerRepoPullsNewRoute
  '/$owner/$repo/pulls/': typeof OwnerRepoPullsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claim'
    | '/device'
    | '/explore'
    | '/login'
    | '/new'
    | '/settings'
    | '/$owner/$repo'
    | '/login/passkey'
    | '/$owner/'
    | '/$owner/$repo/blob'
    | '/$owner/$repo/commits'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/'
    | '/$owner/$repo/commit/$sha'
    | '/$owner/$repo/pull/$number'
    | '/$owner/$repo/pulls/new'
    | '/$owner/$repo/pulls/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claim'
    | '/device'
    | '/explore'
    | '/login'
    | '/new'
    | '/settings'
    | '/login/passkey'
    | '/$owner'
    | '/$owner/$repo/blob'
    | '/$owner/$repo/commits'
    | '/$owner/$repo/settings'
    | '/$owner/$repo'
    | '/$owner/$repo/commit/$sha'
    | '/$owner/$repo/pull/$number'
    | '/$owner/$repo/pulls/new'
    | '/$owner/$repo/pulls'
  id:
    | '__root__'
    | '/'
    | '/claim'
    | '/device'
    | '/explore'
    | '/login'
    | '/new'
    | '/settings'
    | '/$owner/$repo'
    | '/login_/passkey'
    | '/$owner/'
    | '/$owner/$repo/blob'
    | '/$owner/$repo/commits'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/'
    | '/$owner/$repo/commit/$sha'
    | '/$owner/$repo/pull/$number'
    | '/$owner/$repo/pulls/new'
    | '/$owner/$repo/pulls/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimRoute: typeof ClaimRoute
  DeviceRoute: typeof DeviceRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  SettingsRoute: typeof SettingsRoute
  OwnerRepoRouteRoute: typeof OwnerRepoRouteRouteWithChildren
  LoginPasskeyRoute: typeof LoginPasskeyRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/': {
      id: '/$owner/'
      path: '/$owner'
      fullPath: '/$owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo': {
      id: '/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof OwnerRepoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/passkey': {
      id: '/login_/passkey'
      path: '/login/passkey'
      fullPath: '/login/passkey'
      preLoaderRoute: typeof LoginPasskeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof OwnerRepoRouteRoute
    }
    '/$owner/$repo/blob': {
      id: '/$owner/$repo/blob'
      path: '/blob'
      fullPath: '/$owner/$repo/blob'
      preLoaderRoute: typeof OwnerRepoBlobRouteImport
      parentRoute: typeof OwnerRepoRouteRoute
    }
    '/$owner/$repo/commits': {
      id: '/$owner/$repo/commits'
      path: '/commits'
      fullPath: '/$owner/$repo/commits'
      preLoaderRoute: typeof OwnerRepoCommitsRouteImport
      parentRoute: typeof OwnerRepoRouteRoute
    }
    '/$owner/$repo/settings': {
      id: '/$owner/$repo/settings'
      path: '/settings'
      fullPath: '/$owner/$repo/settings'
      preLoaderRoute: typeof OwnerRepoSettingsRouteImport
      parentRoute: typeof OwnerRepoRouteRoute
    }
    '/$owner/$repo/commit/$sha': {
      id: '/$owner/$repo/commit/$sha'
      path: '/commit/$sha'
      fullPath: '/$owner/$repo/commit/$sha'
      preLoaderRoute: typeof OwnerRepoCommitShaRouteImport
      parentRoute: typeof OwnerRepoRouteRoute
    }
    '/$owner/$repo/pull/$number': {
      id: '/$owner/$repo/pull/$number'
      path: '/pull/$number'
      fullPath: '/$owner/$repo/pull/$number'
      preLoaderRoute: typeof OwnerRepoPullNumberRouteImport
      parentRoute: typeof OwnerRepoRouteRoute
    }
    '/$owner/$repo/pulls/': {
      id: '/$owner/$repo/pulls/'
      path: '/pulls'
      fullPath: '/$owner/$repo/pulls/'
      preLoaderRoute: typeof OwnerRepoPullsIndexRouteImport
      parentRoute: typeof OwnerRepoRouteRoute
    }
    '/$owner/$repo/pulls/new': {
      id: '/$owner/$repo/pulls/new'
      path: '/pulls/new'
      fullPath: '/$owner/$repo/pulls/new'
      preLoaderRoute: typeof OwnerRepoPullsNewRouteImport
      parentRoute: typeof OwnerRepoRouteRoute
    }
  }
}

interface OwnerRepoRouteRouteChildren {
  OwnerRepoBlobRoute: typeof OwnerRepoBlobRoute
  OwnerRepoCommitsRoute: typeof OwnerRepoCommitsRoute
  OwnerRepoSettingsRoute: typeof OwnerRepoSettingsRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
  OwnerRepoCommitShaRoute: typeof OwnerRepoCommitShaRoute
  OwnerRepoPullNumberRoute: typeof OwnerRepoPullNumberRoute
  OwnerRepoPullsNewRoute: typeof OwnerRepoPullsNewRoute
  OwnerRepoPullsIndexRoute: typeof OwnerRepoPullsIndexRoute
}

const OwnerRepoRouteRouteChildren: OwnerRepoRouteRouteChildren = {
  OwnerRepoBlobRoute: OwnerRepoBlobRoute,
  OwnerRepoCommitsRoute: OwnerRepoCommitsRoute,
  OwnerRepoSettingsRoute: OwnerRepoSettingsRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
  OwnerRepoCommitShaRoute: OwnerRepoCommitShaRoute,
  OwnerRepoPullNumberRoute: OwnerRepoPullNumberRoute,
  OwnerRepoPullsNewRoute: OwnerRepoPullsNewRoute,
  OwnerRepoPullsIndexRoute: OwnerRepoPullsIndexRoute,
}

const OwnerRepoRouteRouteWithChildren = OwnerRepoRouteRoute._addFileChildren(
  OwnerRepoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimRoute: ClaimRoute,
  DeviceRoute: DeviceRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  SettingsRoute: SettingsRoute,
  OwnerRepoRouteRoute: OwnerRepoRouteRouteWithChildren,
  LoginPasskeyRoute: LoginPasskeyRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
